"""
Manual test for news API - use browser instead of curl
"""

print("🧪 News API Manual Test Guide")
print("=" * 50)
print()
print("🚀 1. Start the Python service:")
print("   cd python-service")
print("   python start_service.py")
print()
print("🌐 2. Open these URLs in your browser:")
print()
print("📂 Health Check:")
print("   http://localhost:8001/health")
print()
print("📂 News Categories:")
print("   http://localhost:8001/news/categories")
print()
print("📂 All News (5 items):")
print("   http://localhost:8001/news?limit=5")
print()
print("📂 CafeF News (3 items):")
print("   http://localhost:8001/news/cafef?limit=3")
print()
print("📂 VnExpress News (3 items):")
print("   http://localhost:8001/news/vnexpress?limit=3")
print()
print("📂 VnStock News:")
print("   http://localhost:8001/news/vnstock")
print()
print("📂 Filter by Category:")
print("   http://localhost:8001/news?category=market&limit=3")
print()
print("📂 Filter by Sentiment:")
print("   http://localhost:8001/news?sentiment=positive&limit=3")
print()
print("📂 Filter by Symbol:")
print("   http://localhost:8001/news?symbols=VCB&limit=3")
print()
print("✅ Expected Results:")
print("   - Categories: JSON array with 6 categories")
print("   - News endpoints: JSON with articles array")
print("   - Each article should have: id, title, summary, source, etc.")
print()
print("🔧 If you see sample data, the API is working!")
print("🔧 If you see real RSS data, even better!")
print()
print("📝 Next step: Test in your React app at http://localhost:3000/news")
